# Generated by Django 3.2.6 on 2022-07-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=10, verbose_name='Venue')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Time start')),
                ('end_time', models.TimeField(verbose_name='Time end')),
                ('event', models.CharField(max_length=10, verbose_name='Event')),
                ('instructor', models.CharField(max_length=20, verbose_name='Instructor')),
            ],
        ),
    ]
