# Generated by Django 3.2.6 on 2022-07-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_request_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='venue',
            field=models.CharField(max_length=255),
        ),
    ]
