# Generated by Django 3.2.6 on 2022-07-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_request_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='order',
            field=models.CharField(default='asc', max_length=10),
        ),
        migrations.AddField(
            model_name='request',
            name='sort',
            field=models.CharField(default='venue', max_length=10),
        ),
    ]
