# Generated by Django 3.2.6 on 2022-07-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=3, verbose_name='ID')),
                ('node_loc', models.CharField(max_length=10, verbose_name='Location')),
                ('temp', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Temperature')),
                ('humi', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Humidity')),
                ('light', models.IntegerField(verbose_name='Light Intensity')),
                ('snd', models.IntegerField(verbose_name='Sound Level')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
