# Generated by Django 3.2.6 on 2022-07-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_rename_humi_event_hum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='light',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Light Intensity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='snd',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Sound Level'),
        ),
    ]
